### ISSUE TITLE
Korora 21 Beta Pharlap startup error

### ISSUE THREAD

**Issue by aldorgan** [kororaproject/kp-pharlap#14]
Hi!
I got this error message when i'm trying to start up pharlap from gnome-terminal:

Traceback (most recent call last):
File "/bin/pharlap", line 130, in 
system = System().to_dict()
File "/usr/lib/python3.4/site-packages/lens/system.py", line 42, in init
self._build_cpu_info()
File "/usr/lib/python3.4/site-packages/lens/system.py", line 83, in _build_cpu_info
self._cpu['clockMax'] = int(float(m.group(1)) * 1e6)
ValueError: could not convert string to float: '1000,0000'

**Comment by firnsy** [comment]
@aldorgan, thanks for the issue, i'm currently fixing the locale conversion issue at the moment.
